/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/agent/handoffs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Handoffs
         * @description Escalated cases, high priority first, then the oldest. ``search`` matches part of the
         *     handoff ID the customer was given (HO-...), the conversation ID, the customer reference or the
         *     request summary.
         */
        get: operations["list_handoffs_api_agent_handoffs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/handoffs/{handoff_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Handoff */
        get: operations["get_handoff_api_agent_handoffs__handoff_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Agent Metrics
         * @description The same metrics as /api/audit/metrics, for the console.
         */
        get: operations["agent_metrics_api_agent_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check Session
         * @description 204 if the token proves the agent role, 403 otherwise: the console's sign-in check. Recorded
         *     like any other read.
         */
        get: operations["check_session_api_agent_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Traces
         * @description Turn traces, newest first, as summaries. ``search`` matches part of a trace,
         *     conversation, session or handoff ID; the full trace is read from /api/audit/{trace_id}.
         */
        get: operations["search_traces_api_agent_traces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Traces */
        get: operations["list_traces_api_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description Outcomes, containment, escalations, latency p50/p95, cost, by language and tier.
         */
        get: operations["metrics_api_audit_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit/{trace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trace */
        get: operations["get_trace_api_audit__trace_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/turn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Turn */
        post: operations["turn_api_turn_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ui/texts/{language}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Texts */
        get: operations["texts_api_ui_texts__language__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Request an OTP. The response is identical whether or not the document exists.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Session */
        get: operations["current_session_auth_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify */
        post: operations["verify_auth_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionId
         * @description Policy §8. ACT-06 (prohibited actions) is intentionally absent: it is never authorized.
         * @enum {string}
         */
        ActionId: "ACT-01" | "ACT-02" | "ACT-03" | "ACT-04" | "ACT-05";
        /**
         * ActionTaken
         * @description An attempted action with its verification result. Failed actions are included.
         */
        ActionTaken: {
            action: components["schemas"]["ActionId"];
            /** At */
            at?: string | null;
            /** Detail */
            detail?: string | null;
            result: components["schemas"]["ToolStatus"];
            /** Verified */
            verified: boolean;
        };
        /** AuditMetrics */
        AuditMetrics: {
            /** Abandoned */
            abandoned: number;
            /** Attempted Cases */
            attempted_cases: number;
            /** Automated Resolutions */
            automated_resolutions: number;
            /** Contained */
            contained: number;
            /** Containment Rate */
            containment_rate: number | null;
            /** Conversations */
            conversations: number;
            /** Cost Per Attempted Case Usd */
            cost_per_attempted_case_usd: string | null;
            /** Cost Per Automated Resolution Usd */
            cost_per_automated_resolution_usd: string | null;
            /** Ended Before Transaction */
            ended_before_transaction: {
                [key: string]: number;
            };
            /** Escalated */
            escalated: number;
            /** Escalation Rate */
            escalation_rate: number | null;
            /** Escalations By Queue */
            escalations_by_queue: {
                [key: string]: number;
            };
            /** Escalations By Rule */
            escalations_by_rule: {
                [key: string]: number;
            };
            /** Outcomes */
            outcomes: {
                [key: string]: number;
            };
            /** Outcomes By Language */
            outcomes_by_language?: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /** Outcomes By Tier */
            outcomes_by_tier?: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /** Stage Latency */
            stage_latency: {
                [key: string]: components["schemas"]["LatencySummary"];
            };
            /** Total Cost Usd */
            total_cost_usd: string | null;
            turn_latency: components["schemas"]["LatencySummary"];
            /** Turns */
            turns: number;
            /** Turns Without Cost */
            turns_without_cost: number;
        };
        /**
         * AuthStatus
         * @enum {string}
         */
        AuthStatus: "authenticated" | "unauthenticated" | "expired";
        /**
         * CaseStatus
         * @description docs/diagrams/dispute-case-lifecycle.md.
         * @enum {string}
         */
        CaseStatus: "Draft" | "Open" | "Escalated" | "In Process" | "Resolved" | "Rejected" | "Closed";
        /**
         * ClarifyTarget
         * @description What a CLARIFY turn asks for: a §10 slot, the language (GATE-01), or
         *     authentication (GATE-02).
         * @enum {string}
         */
        ClarifyTarget: "transaction_ref" | "reason_code" | "card_in_possession" | "shared_credentials" | "duplicate_ref" | "expected_amount" | "expected_delivery_date" | "merchant_contacted" | "fee_ref" | "confirmation" | "language" | "authentication" | "correction";
        /**
         * CollectedSlot
         * @description A slot the customer already gave: a claim, never verified (DATA-03).
         */
        CollectedSlot: {
            name: components["schemas"]["SlotName"];
            /** Turn Index */
            turn_index?: number | null;
            /** Value */
            value: string;
            /**
             * Verified
             * @default false
             * @constant
             */
            verified: false;
        };
        /** DraftCase */
        DraftCase: {
            /** Amount Usd */
            amount_usd?: string | null;
            provisional_credit_flag?: components["schemas"]["ProvisionalCreditFlag"] | null;
            tier?: components["schemas"]["Tier"] | null;
            /** Transaction Ref */
            transaction_ref: string;
        };
        /**
         * EscalationReason
         * @description A triggered rule in plain words, with the evidence that made it fire.
         */
        EscalationReason: {
            /** Description */
            description: string;
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /** Rule Id */
            rule_id: string;
        };
        /**
         * Evidence
         * @description One input that made a rule fire. Taken from the request, never generated.
         */
        Evidence: {
            /** Claims */
            claims?: string[];
            kind: components["schemas"]["EvidenceKind"];
            /** Name */
            name: string;
            /** Origin */
            origin: string;
            /** Record Id */
            record_id?: string | null;
            /** Source */
            source?: string | null;
            /** Value */
            value: string;
        };
        /**
         * EvidenceKind
         * @description Where a piece of evidence for a fired rule comes from.
         * @enum {string}
         */
        EvidenceKind: "slot" | "flag" | "counter" | "record" | "signal" | "tool_result" | "input_guard" | "language";
        /** GateResult */
        GateResult: {
            /** Gate Id */
            gate_id: string;
            /** Passed */
            passed: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HandoffAuth */
        HandoffAuth: {
            /** Method */
            method?: string | null;
            /** Session Age Min */
            session_age_min?: number | null;
            status: components["schemas"]["AuthStatus"];
        };
        /**
         * HandoffModelSignals
         * @description Informative model output shown to the agent (never a decision).
         */
        HandoffModelSignals: {
            /**
             * Calibrated
             * @default false
             */
            calibrated: boolean;
            /** Escalation Risk */
            escalation_risk?: number | null;
            /** Model Info */
            model_info?: {
                [key: string]: string;
            };
            /** Model Version */
            model_version?: string | null;
            /** Reason Code Other */
            reason_code_other?: number | null;
            /** Reason Code Probs */
            reason_code_probs?: {
                [key: string]: number;
            };
            source?: components["schemas"]["ModelSource"] | null;
        };
        /**
         * HandoffPacket
         * @description Policy §13. Never contains the raw transcript, only ``transcript_ref``.
         */
        HandoffPacket: {
            /** Actions Taken */
            actions_taken?: components["schemas"]["ActionTaken"][];
            auth: components["schemas"]["HandoffAuth"];
            /**
             * Business Date
             * Format: date
             */
            business_date: string;
            /** Collected Slots */
            collected_slots?: components["schemas"]["CollectedSlot"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Customer Claims */
            customer_claims?: string[];
            /** Customer Ref */
            customer_ref: string;
            draft_case?: components["schemas"]["DraftCase"] | null;
            /** Escalation Reasons */
            escalation_reasons?: components["schemas"]["EscalationReason"][];
            /** Handoff Id */
            handoff_id: string;
            language: components["schemas"]["Language"];
            model_signals?: components["schemas"]["HandoffModelSignals"];
            /** Open Questions */
            open_questions?: string[];
            /** Policy Version */
            policy_version: string;
            /** Post Handoff Messages */
            post_handoff_messages?: components["schemas"]["PostHandoffMessage"][];
            priority: components["schemas"]["Priority"];
            queue: components["schemas"]["Queue"];
            reason_code?: components["schemas"]["ReasonCode"] | null;
            /** Request Summary */
            request_summary: string;
            /** Transcript Ref */
            transcript_ref: string;
            /** Triggered Rules */
            triggered_rules: string[];
            /** Verified Facts */
            verified_facts?: components["schemas"]["VerifiedFact"][];
        };
        /** HandoffPage */
        HandoffPage: {
            /** Items */
            items: components["schemas"]["HandoffSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * HandoffSummary
         * @description One line of the queue: enough to choose a case without opening it.
         */
        HandoffSummary: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Handoff Id */
            handoff_id: string;
            language: components["schemas"]["Language"];
            priority: components["schemas"]["Priority"];
            queue: components["schemas"]["Queue"];
            /** Request Summary */
            request_summary: string;
            /** Status */
            status: string;
            /** Triggered Rules */
            triggered_rules: string[];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Policy Version */
            policy_version: string;
            /** Status */
            status: string;
        };
        /**
         * InformReason
         * @description Why an INFORM outcome was produced. Each value maps to a versioned template (COM-02).
         * @enum {string}
         */
        InformReason: "authentication_declined" | "authentication_attempts_exceeded" | "transaction_pending" | "transaction_declined" | "transaction_reversed" | "not_disputable" | "outside_window" | "duplicate_case" | "amount_not_exceeded" | "delivery_date_not_reached" | "merchant_not_contacted" | "dispute_withdrawn";
        /**
         * InputGuardResult
         * @description Input Guard output for one message (ESC-13).
         */
        InputGuardResult: {
            /**
             * Escalate Security
             * @default false
             */
            escalate_security: boolean;
            /** Flagged */
            flagged: boolean;
            /** Pattern Id */
            pattern_id?: string | null;
            /** Strikes */
            strikes: number;
        };
        /** IssuedSession */
        IssuedSession: {
            /** Access Token */
            access_token: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Session Id */
            session_id: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * Language
         * @description Supported conversation languages (GATE-01, COM-01).
         * @enum {string}
         */
        Language: "es" | "pt";
        /** LatencySummary */
        LatencySummary: {
            /** Count */
            count: number;
            /** P50 Ms */
            p50_ms: number | null;
            /** P95 Ms */
            p95_ms: number | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Document Number */
            document_number: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Expires In Seconds */
            expires_in_seconds: number;
            /**
             * Status
             * @default otp_sent
             */
            status: string;
        };
        /** ModelCall */
        ModelCall: {
            /** Adjustments */
            adjustments?: string[];
            /** Cached Input Tokens */
            cached_input_tokens?: number | null;
            /** Error */
            error?: string | null;
            /** Input Tokens */
            input_tokens?: number | null;
            /** Latency Ms */
            latency_ms: number;
            /** Model */
            model: string;
            /** Model Info */
            model_info?: {
                [key: string]: string;
            };
            /** Output Tokens */
            output_tokens?: number | null;
            /** Prompt Hash */
            prompt_hash?: string | null;
            /** Prompt Version */
            prompt_version?: string | null;
            /** Provider */
            provider: string;
            /** Purpose */
            purpose: string;
            /** Response Model */
            response_model?: string | null;
            /** Server Latency Ms */
            server_latency_ms?: number | null;
            /** Success */
            success: boolean;
            /** System Fingerprint */
            system_fingerprint?: string | null;
        };
        /**
         * ModelSignals
         * @description Decision-layer output (architecture §3). Informative only; never a decision.
         *
         *     How the Policy Engine may use these signals (M8):
         *
         *     - ``source`` says where they came from: ``kev`` (the decision model), ``llm_fallback``
         *       (derived from the current message's extraction when Kev is unavailable: 0/1 values,
         *       deliberately uncalibrated; it is the baseline Kev is evaluated against in M18), or
         *       ``unavailable`` (all empty: treat as uncertainty, ESC-11).
         *     - As served, Kev's ``ambiguity`` and ``escalation_risk`` sit near 0.5 (0.51-0.60 on the
         *       verified cases). They must not influence any decision until M7 recalibrates the
         *       temperature per question on the validation split; until then the ESC-11 thresholds stay
         *       null.
         *     - ``reason_code_probs`` is informative: it never replaces the reason code the customer
         *       states and confirms. ``reason_code_other`` is the probability of a reason outside the
         *       five codes; with it the distribution is complete (never renormalized).
         */
        ModelSignals: {
            /** Ambiguity */
            ambiguity?: number | null;
            /** Escalation Risk */
            escalation_risk?: number | null;
            /** Manipulation */
            manipulation?: number | null;
            /** Model Info */
            model_info?: {
                [key: string]: string;
            };
            /** Model Version */
            model_version?: string | null;
            /** Reason Code Other */
            reason_code_other?: number | null;
            /** Reason Code Probs */
            reason_code_probs?: {
                [key: string]: number;
            };
            source: components["schemas"]["ModelSource"];
        };
        /**
         * ModelSource
         * @description Where decision-layer signals came from (architecture §3, §8).
         * @enum {string}
         */
        ModelSource: "kev" | "llm_fallback" | "unavailable";
        /**
         * Outcome
         * @description Policy §9. Precedence: REFUSE > ESCALATE > INFORM > CLARIFY > RESOLVE.
         * @enum {string}
         */
        Outcome: "RESOLVE" | "CLARIFY" | "INFORM" | "ESCALATE" | "REFUSE";
        /**
         * PolicyDecision
         * @description Policy Engine output for one disputed transaction.
         */
        PolicyDecision: {
            /** Amount Usd */
            amount_usd?: string | null;
            ask_for?: components["schemas"]["TransactionField"] | null;
            /** Authorized Actions */
            authorized_actions?: components["schemas"]["ActionId"][];
            /** Candidate Transaction Ids */
            candidate_transaction_ids?: string[];
            /**
             * Card Already Blocked
             * @default false
             */
            card_already_blocked: boolean;
            /** Card Product Id */
            card_product_id?: string | null;
            clarify_target?: components["schemas"]["ClarifyTarget"] | null;
            /**
             * Duplicate Reason Reask
             * @default false
             */
            duplicate_reason_reask: boolean;
            /** Duplicate Transaction Id */
            duplicate_transaction_id?: string | null;
            /** Evidence */
            evidence?: components["schemas"]["RuleEvidence"][];
            /** Existing Case Id */
            existing_case_id?: string | null;
            existing_case_status?: components["schemas"]["CaseStatus"] | null;
            /** Gates Evaluated */
            gates_evaluated?: components["schemas"]["GateResult"][];
            inform_reason?: components["schemas"]["InformReason"] | null;
            /** Notes */
            notes?: string[];
            outcome: components["schemas"]["Outcome"];
            /** Policy Version */
            policy_version: string;
            priority?: components["schemas"]["Priority"] | null;
            provisional_credit_flag?: components["schemas"]["ProvisionalCreditFlag"] | null;
            queue?: components["schemas"]["Queue"] | null;
            reason_code?: components["schemas"]["ReasonCode"] | null;
            tier?: components["schemas"]["Tier"] | null;
            /** Transaction Id */
            transaction_id?: string | null;
            transaction_search?: components["schemas"]["TransactionSearch"] | null;
            /** Triggered Rules */
            triggered_rules?: string[];
        };
        /**
         * PostHandoffMessage
         * @description A message the customer wrote after the handoff, masked, read by no model.
         */
        PostHandoffMessage: {
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Text */
            text: string;
        };
        /**
         * Priority
         * @enum {string}
         */
        Priority: "normal" | "high";
        /**
         * ProvisionalCreditFlag
         * @description Policy §6. For T3 the flag is decided by a human, so it is absent (None).
         * @enum {string}
         */
        ProvisionalCreditFlag: "eligible" | "requires_review";
        /**
         * Queue
         * @description Escalation routes named in policy §7.
         * @enum {string}
         */
        Queue: "disputes" | "fraud" | "security_review";
        /**
         * ReasonCode
         * @description Policy §3.
         * @enum {string}
         */
        ReasonCode: "RC_UNRECOGNIZED" | "RC_DUPLICATE" | "RC_INCORRECT_AMOUNT" | "RC_NOT_RECEIVED" | "RC_FEE";
        /** RuleEvidence */
        RuleEvidence: {
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /** Rule Id */
            rule_id: string;
        };
        /** SessionResponse */
        SessionResponse: {
            /** Customer Id */
            customer_id: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            /**
             * Last Activity At
             * Format: date-time
             */
            last_activity_at: string;
            /** Session Id */
            session_id: string;
        };
        /**
         * SideQuestion
         * @description A question the customer asks instead of (or besides) answering. The Orchestrator answers
         *     it with a template and then goes on with the flow; it is not a clarification.
         * @enum {string}
         */
        SideQuestion: "refund" | "timeline" | "block_consequences" | "case_status" | "card_status" | "flow_help" | "other";
        /**
         * SlotName
         * @description Policy §10, in the order the system asks for them.
         * @enum {string}
         */
        SlotName: "transaction_ref" | "reason_code" | "card_in_possession" | "shared_credentials" | "duplicate_ref" | "expected_amount" | "expected_delivery_date" | "merchant_contacted" | "fee_ref" | "confirmation";
        /**
         * Tier
         * @description Policy §6.
         * @enum {string}
         */
        Tier: "T1" | "T2" | "T3";
        /**
         * ToolResult
         * @description Result of one Tool Layer write action (ACT-02, ACT-03, ACT-05).
         *
         *     For write actions with read-back verification, ``success`` implies ``verified`` and
         *     ``verified`` implies ``success`` (policy §8, COM-04).
         */
        ToolResult: {
            action: components["schemas"]["ActionId"];
            /** Attempts */
            attempts: number;
            /** Completed At */
            completed_at?: string | null;
            /** Detail */
            detail?: string | null;
            /** Error */
            error?: string | null;
            /** Idempotency Key */
            idempotency_key?: string | null;
            /** Record Id */
            record_id?: string | null;
            status: components["schemas"]["ToolStatus"];
            /** Verified */
            verified: boolean;
        };
        /**
         * ToolStatus
         * @enum {string}
         */
        ToolStatus: "success" | "failed" | "access_denied";
        /** TracePage */
        TracePage: {
            /** Items */
            items: components["schemas"]["TraceSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * TraceRecord
         * @description One record per turn. Optional stages that did not run are recorded as None.
         */
        TraceRecord: {
            /** Conversation Id */
            conversation_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Decisions */
            decisions?: components["schemas"]["PolicyDecision"][];
            /** Error */
            error?: string | null;
            /** Estimated Cost Usd */
            estimated_cost_usd?: string | null;
            /** Handoff Id */
            handoff_id?: string | null;
            input_guard?: components["schemas"]["InputGuardResult"] | null;
            language?: components["schemas"]["Language"] | null;
            /** Message */
            message?: string | null;
            /** Model Calls */
            model_calls?: components["schemas"]["ModelCall"][];
            outcome?: components["schemas"]["Outcome"] | null;
            /** Policy Version */
            policy_version: string;
            /** Reply Kind */
            reply_kind?: string | null;
            /** Session Id */
            session_id?: string | null;
            side_question?: components["schemas"]["SideQuestion"] | null;
            signals?: components["schemas"]["ModelSignals"] | null;
            /** Stage Latencies Ms */
            stage_latencies_ms?: {
                [key: string]: number;
            };
            /** Tool Calls */
            tool_calls?: components["schemas"]["ToolResult"][];
            /** Total Latency Ms */
            total_latency_ms?: number | null;
            /** Trace Id */
            trace_id: string;
            /** Turn Index */
            turn_index: number;
        };
        /**
         * TraceSummary
         * @description One line of the console's trace list: enough to choose a turn without loading it.
         */
        TraceSummary: {
            /** Conversation Id */
            conversation_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Estimated Cost Usd */
            estimated_cost_usd: string | null;
            /** Handoff Id */
            handoff_id: string | null;
            language: components["schemas"]["Language"] | null;
            outcome: components["schemas"]["Outcome"] | null;
            /** Reply Kind */
            reply_kind: string | null;
            /** Session Id */
            session_id: string | null;
            /** Total Latency Ms */
            total_latency_ms: number | null;
            /** Trace Id */
            trace_id: string;
            /** Turn Index */
            turn_index: number;
        };
        /**
         * TransactionField
         * @description A detail of a transaction reference the customer can be asked for.
         * @enum {string}
         */
        TransactionField: "merchant" | "transaction_date" | "amount";
        /**
         * TransactionSearch
         * @description Why GATE-05 did not identify the transaction (policy §5, "Transaction matching").
         * @enum {string}
         */
        TransactionSearch: "no_match" | "too_many" | "relaxed";
        /** TurnRequest */
        TurnRequest: {
            /** Conversation Id */
            conversation_id?: string | null;
            /** Message */
            message: string;
        };
        /** TurnResponse */
        TurnResponse: {
            /** Case Reference */
            case_reference?: string | null;
            /** Conversation Id */
            conversation_id: string;
            /** Handed Off */
            handed_off: boolean;
            /** Handoff Reference */
            handoff_reference?: string | null;
            language: components["schemas"]["Language"] | null;
            /** Reply */
            reply: string;
            /**
             * Status
             * @enum {string}
             */
            status: "in_progress" | "awaiting_confirmation" | "authentication_required" | "case_created" | "handed_off";
            /** Trace Id */
            trace_id: string;
            /** Turn Index */
            turn_index: number;
        };
        /**
         * UiTexts
         * @description One language's catalog, as the frontend receives it.
         */
        UiTexts: {
            /** Language */
            language: string;
            /** Texts */
            texts: {
                [key: string]: string;
            };
            /** Version */
            version: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VerifiedFact
         * @description DATA-04: every verified fact names its source table and record ID.
         */
        VerifiedFact: {
            /** Fact */
            fact: string;
            /** Record Id */
            record_id: string;
            /** Source */
            source: string;
        };
        /** VerifyRequest */
        VerifyRequest: {
            /** Document Number */
            document_number: string;
            /** Otp */
            otp: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_handoffs_api_agent_handoffs_get: {
        parameters: {
            query?: {
                queue?: components["schemas"]["Queue"] | null;
                priority?: components["schemas"]["Priority"] | null;
                since?: string | null;
                search?: string | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HandoffPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_handoff_api_agent_handoffs__handoff_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handoff_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HandoffPacket"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agent_metrics_api_agent_metrics_get: {
        parameters: {
            query?: {
                conversation_id?: string | null;
                session_id?: string | null;
                outcome?: components["schemas"]["Outcome"] | null;
                language?: components["schemas"]["Language"] | null;
                since?: string | null;
                until?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditMetrics"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_session_api_agent_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    search_traces_api_agent_traces_get: {
        parameters: {
            query?: {
                search?: string | null;
                outcome?: components["schemas"]["Outcome"] | null;
                language?: components["schemas"]["Language"] | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TracePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_traces_api_audit_get: {
        parameters: {
            query?: {
                conversation_id?: string | null;
                session_id?: string | null;
                outcome?: components["schemas"]["Outcome"] | null;
                language?: components["schemas"]["Language"] | null;
                since?: string | null;
                until?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_api_audit_metrics_get: {
        parameters: {
            query?: {
                conversation_id?: string | null;
                session_id?: string | null;
                outcome?: components["schemas"]["Outcome"] | null;
                language?: components["schemas"]["Language"] | null;
                since?: string | null;
                until?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditMetrics"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trace_api_audit__trace_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    turn_api_turn_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    texts_api_ui_texts__language__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                language: "es" | "pt";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UiTexts"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    current_session_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    verify_auth_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuedSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
